name: Build and test machine learning client
on: [push, pull_request]

jobs:
  build-ml-client:
    name: build and test ML client with pipenv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./machine-learning-client
    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
          working-directory: ./machine-learning-client

      - name: Regenerate lock file
        run: |
          pipenv lock

      - name: Install dependencies
        run: |
          pipenv install pytest pytest-flask coverage mongomock

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Test with pytest
        env:
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pipenv run python -m pytest

      - name: Test with coverage
        env:
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage report -i
