name: Build and test Flask web app
on: [push, pull_request]

jobs:
  build-web-app:
    name: build and test web app with pipenv
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
          working-directory: ./web-app

      - name: Regenerate lock file
        run: |
          pipenv lock
      - name: Install dependencies
        run: |
          pipenv install pytest pytest-flask coverage

      - name: Test with pytest
        env: 
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pipenv run python -m pytest

      - name: Test with coverage
        env: 
            MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
            MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage report -i

      
